<?php

return array(
    "FEEDBACK_INVALID_USERNAME_FORMAT" => "",
    "FEEDBACK_EMPTY_EMAIL" => "",
    "FEEDBACK_EMAIL_REPEAT_WRONG" => "",
    "FEEDBACK_INVALID_EMAIL_FORMAT" => "",
    "FEEDBACK_EMPTY_PASSWORD" => "",
    "FEEDBACK_PASSWORD_REPEAT_WRONG" => "",
    "FEEDBACK_INVALID_PASSWORD_FORMAT" => "",
);
